default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: giancarlo
  password: password

development:
  <<: *default
  database: basic_api

test:
  <<: *default
  database: basic_api_test

production:
  <<: *default
  database: basic_api_prd
